name: Create and package Java app with Maven, then create Docker image and push to dockerhub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on:  ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag built2lead/getting-started:1.0.0
         
      - name: Login to Dockerhub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: Build and push
        run: docker push built2lead/getting-started:1.0.0
